// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/howie/Documents/project/antd-flutter/docs/node_modules/dumi-theme-antd/dist/builtins/BashOSPlatform/index.js';
