// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/howie/Documents/project/antd-flutter/docs/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.23.6_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@19.1._a09416131a5eb856c33861395270ef7f/node_modules/dumi/theme-default/builtins/Table/index.js';
