name: Deploy Flutter dumi Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dumi dependencies
        working-directory: ./docs
        run: pnpm install

      - name: Build dumi docs
        working-directory: ./docs
        run: pnpm run build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Add .nojekyll file
        working-directory: ./docs/dist
        run: touch .nojekyll

      - name: List built files
        working-directory: ./docs/dist
        run: ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Build Flutter Web
        working-directory: ./example
        run: |
          flutter pub get
          flutter build web --release --base-href /antd-flutter/ --wasm

      - name: Deploy to Separate Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
          publish_branch: example
